import "./globals.css";
import { Roboto, Montserrat, Istok_Web } from "next/font/google";
import Toast, { ToastContextProvider } from "@/components/Toast";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
  variable: "--font-roboto",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["700"],
  display: "swap",
  variable: "--font-montserrat",
});

const istokWeb = Istok_Web({
  subsets: ["latin"],
  weight: ["700"],
  display: "swap",
  variable: "--font-istok-web",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const toastState = {
    visible: false,
  };

  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${istokWeb.variable} ${roboto.variable} font-sans`}
    >
      <body>
        <main className="min-h-screen flex flex-col">
          <div className="px-6 py-4 text-2xl font-istok-web">Notizo</div>
          <div className="flex justify-center flex-grow">
            <ToastContextProvider>
              <div className="flex flex-col w-full max-w-sm mt-[10vh] px-6">
                {children}
              </div>
              <Toast />
            </ToastContextProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
